import { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { Activity, Clock, Crosshair, RefreshCw, ShieldCheck, Target, Trophy } from 'lucide-react';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Skeleton } from '@/components/ui/skeleton';

type MarketTab='moneyline'|'anytime'|'firsttd';
type BookQuote={bookmaker:string;bookmakerKey:string;americanOdds:number;updatedAt:string|null};
type PlayerMarket={player:string;bestOdds:number;bestBook:string;impliedProbability:number;quoteCount:number;quotes:BookQuote[]};
type MoneylineSide={team:string;bestOdds:number|null;bestBook:string|null;impliedProbability:number|null;consensusNoVigProbability:number|null;quotes:BookQuote[]};
type NflGame={id:string;date:string;status:string;away:{abbreviation:string;name:string;logo:string|null;record:string|null};home:{abbreviation:string;name:string;logo:string|null;record:string|null};marketStatus:'available'|'unavailable';moneyline:{away:MoneylineSide;home:MoneylineSide}|null;anytimeTd:PlayerMarket[];firstTd:PlayerMarket[]};
type NflFeed={source:string;marketStatus:'available'|'unavailable'|'disabled';updatedAt:string;games:NflGame[]};

function formatTime(v:string){const d=new Date(v);return Number.isNaN(d.getTime())?'Time pending':d.toLocaleString('en-US',{weekday:'short',month:'short',day:'numeric',hour:'numeric',minute:'2-digit',timeZone:'America/New_York'})+' ET'}
function odds(v:number|null){if(v===null||!Number.isFinite(v))return '—';return v>0?`+${Math.round(v)}`:`${Math.round(v)}`}

const BOOK_DOMAINS:Array<[string,string]>=[['fanduel','fanduel.com'],['draftkings','draftkings.com'],['betmgm','betmgm.com'],['caesars','caesars.com'],['betrivers','betrivers.com'],['fanatics','fanatics.com'],['espnbet','espnbet.com'],['bet365','bet365.com'],['bovada','bovada.lv'],['pinnacle','pinnacle.com'],['hardrock','hardrock.bet'],['betonline','betonline.ag'],['thescore','thescore.bet'],['scorebet','thescore.bet']];
function bookDomain(book:string|null){const key=(book??'').toLowerCase().replace(/[^a-z0-9]/g,'');return BOOK_DOMAINS.find(([needle])=>key.includes(needle))?.[1]??null}
function SportsbookLogo({book}:{book:string|null}){const domain=bookDomain(book);const initial=(book??'S').trim().charAt(0).toUpperCase()||'S';return <span className="flex h-7 w-7 shrink-0 items-center justify-center overflow-hidden rounded-md border bg-white text-[10px] font-black text-black">{domain?<img src={`https://www.google.com/s2/favicons?domain=${domain}&sz=64`} alt={`${book??'Sportsbook'} logo`} className="h-5 w-5 object-contain" onError={e=>{e.currentTarget.style.display='none'}}/>:initial}</span>}

function GameShell({game,children}:{game:NflGame;children:React.ReactNode}){return <article className="overflow-hidden rounded-xl border bg-card shadow-sm"><div className="flex items-center justify-between gap-3 border-b bg-muted/20 px-4 py-3"><div><div className="font-bold text-sm">{game.away.abbreviation} @ {game.home.abbreviation}</div><div className="mt-1 flex items-center gap-1 text-[10px] text-muted-foreground"><Clock className="h-3 w-3"/>{formatTime(game.date)}</div></div><div className="flex items-center gap-2"><Badge variant={game.marketStatus==='available'?'default':'secondary'} className="text-[9px]">{game.marketStatus==='available'?'MARKET LIVE':'PRICING PENDING'}</Badge><Badge variant="secondary">{game.status}</Badge></div></div><div className="p-4"><div className="mb-5 grid grid-cols-[1fr_auto_1fr] items-center gap-3"><div className="flex items-center gap-2">{game.away.logo&&<img src={game.away.logo} alt="" className="h-9 w-9 object-contain"/>}<div><div className="text-sm font-semibold">{game.away.name}</div><div className="text-[10px] text-muted-foreground">{game.away.record??'—'}</div></div></div><span className="text-xs text-muted-foreground">@</span><div className="flex items-center justify-end gap-2 text-right"><div><div className="text-sm font-semibold">{game.home.name}</div><div className="text-[10px] text-muted-foreground">{game.home.record??'—'}</div></div>{game.home.logo&&<img src={game.home.logo} alt="" className="h-9 w-9 object-contain"/>}</div></div>{children}</div></article>}

function MoneylineSideCard({label,side}:{label:string;side:MoneylineSide}){return <div className="rounded-xl border bg-background/55 p-3"><div className="text-[9px] uppercase tracking-wide text-muted-foreground">{label}</div><div className="mt-2 flex items-center justify-between gap-2"><div className="min-w-0"><div className="truncate text-xs font-bold">{side.team}</div><div className="mt-1 font-mono text-2xl font-black">{odds(side.bestOdds)}</div></div><div className="flex items-center gap-2"><SportsbookLogo book={side.bestBook}/><div className="text-right"><div className="max-w-[100px] truncate text-[9px] font-semibold">{side.bestBook??'Sportsbook'}</div><div className="text-[9px] text-muted-foreground">best price</div></div></div></div><div className="mt-3 grid grid-cols-2 gap-2 border-t pt-3"><div><div className="text-[8px] uppercase text-muted-foreground">Implied</div><div className="font-mono text-sm font-bold">{side.impliedProbability===null?'—':`${side.impliedProbability.toFixed(1)}%`}</div></div><div><div className="text-[8px] uppercase text-muted-foreground">No-vig market</div><div className="font-mono text-sm font-bold">{side.consensusNoVigProbability===null?'—':`${side.consensusNoVigProbability.toFixed(1)}%`}</div></div></div></div>}
function MoneylineCard({game}:{game:NflGame}){return <GameShell game={game}>{game.moneyline?<div className="grid grid-cols-2 gap-3"><MoneylineSideCard label={game.away.abbreviation} side={game.moneyline.away}/><MoneylineSideCard label={game.home.abbreviation} side={game.moneyline.home}/></div>:<div className="rounded-xl border bg-muted/15 p-8 text-center"><ShieldCheck className="mx-auto h-7 w-7 text-muted-foreground/40"/><div className="mt-2 text-sm font-semibold">Moneyline pricing pending</div></div>}<div className="mt-3 text-[10px] text-muted-foreground">Sportsbook prices are live market data. A proprietary PreziTools win probability will be added only after the NFL team-strength model is validated.</div></GameShell>}

function PlayerRow({row,index}:{row:PlayerMarket;index:number}){return <div className="grid grid-cols-[30px_minmax(0,1fr)_auto] items-center gap-3 border-b px-3 py-3 last:border-b-0"><div className="flex h-7 w-7 items-center justify-center rounded-full bg-muted text-[10px] font-black">{index+1}</div><div className="min-w-0"><div className="truncate text-sm font-bold">{row.player}</div><div className="mt-1 flex items-center gap-2"><SportsbookLogo book={row.bestBook}/><span className="truncate text-[9px] font-semibold">{row.bestBook}</span><span className="text-[9px] text-muted-foreground">{row.quoteCount} {row.quoteCount===1?'book':'books'}</span></div></div><div className="text-right"><div className="font-mono text-lg font-black">{odds(row.bestOdds)}</div><div className="text-[8px] text-muted-foreground">{row.impliedProbability.toFixed(1)}% implied</div></div></div>}
function PlayerMarketCard({game,first}:{game:NflGame;first:boolean}){const rows=first?game.firstTd:game.anytimeTd;return <GameShell game={game}>{rows.length?<><div className="mb-3 flex items-center justify-between"><div className="flex items-center gap-2"><Crosshair className="h-4 w-4 text-primary"/><div className="text-xs font-bold">{first?'First TD market':'Anytime TD market'}</div></div><Badge variant="outline" className="text-[9px]">{rows.length} players</Badge></div><div className="max-h-[520px] overflow-y-auto rounded-xl border bg-background/35">{rows.map((row,index)=><PlayerRow key={`${game.id}-${first?'first':'any'}-${row.player}`} row={row} index={index}/>)}</div><div className="mt-3 text-[10px] text-muted-foreground">Ranked by sportsbook implied probability for now. These are market prices, not yet proprietary PreziTools TD probabilities.</div></>:<div className="rounded-xl border bg-muted/15 p-8 text-center"><Crosshair className="mx-auto h-7 w-7 text-muted-foreground/40"/><div className="mt-2 text-sm font-semibold">{first?'First TD':'Anytime TD'} pricing pending</div><div className="mt-1 text-[10px] text-muted-foreground">This game will populate automatically when PropLine has the market.</div></div>}</GameShell>}

export default function NFL(){
 const[tab,setTab]=useState<MarketTab>('firsttd');
 const query=useQuery<NflFeed>({queryKey:['/api/nfl/markets'],staleTime:2*60*1000,refetchInterval:5*60*1000,retry:1});
 const games=[...(query.data?.games??[])].sort((a,b)=>new Date(a.date).getTime()-new Date(b.date).getTime());
 const priced=games.filter(g=>g.marketStatus==='available').length;
 const anytimeCount=games.reduce((s,g)=>s+g.anytimeTd.length,0);
 const firstCount=games.reduce((s,g)=>s+g.firstTd.length,0);
 if(query.isLoading)return <div className="space-y-4"><Skeleton className="h-10 w-64"/><Skeleton className="h-28"/><Skeleton className="h-80"/></div>;
 return <div className="-mx-4 -mt-8 md:-mx-6 lg:-mx-8"><div className="border-b bg-card"><div className="mx-auto flex max-w-7xl items-center justify-between px-4 md:px-6 lg:px-8"><div className="flex overflow-x-auto"><button onClick={()=>setTab('firsttd')} className={`whitespace-nowrap border-b-2 px-4 py-4 text-xs ${tab==='firsttd'?'border-primary':'border-transparent text-muted-foreground'}`}>First TD Scorer</button><button onClick={()=>setTab('anytime')} className={`whitespace-nowrap border-b-2 px-4 py-4 text-xs ${tab==='anytime'?'border-primary':'border-transparent text-muted-foreground'}`}>Anytime TD</button><button onClick={()=>setTab('moneyline')} className={`whitespace-nowrap border-b-2 px-4 py-4 text-xs ${tab==='moneyline'?'border-primary':'border-transparent text-muted-foreground'}`}>Moneyline</button></div><Button variant="outline" size="sm" onClick={()=>query.refetch()} className="gap-2"><RefreshCw className={`h-3.5 w-3.5 ${query.isFetching?'animate-spin':''}`}/>Refresh</Button></div></div><div className="mx-auto max-w-7xl px-4 py-6 md:px-6 lg:px-8"><div className="mb-5"><h1 className="text-xl font-bold">NFL Predictions</h1><p className="mt-1 text-xs text-muted-foreground">PreziTools model development + live sportsbook market layer</p></div><div className="mb-6 grid grid-cols-2 gap-4 lg:grid-cols-4"><div className="rounded-xl border bg-card p-4"><Activity className="mb-2 h-4 w-4 text-primary"/><div className="text-2xl font-bold">{games.length}</div><div className="text-xs font-medium">Current Slate</div></div><div className="rounded-xl border bg-card p-4"><Target className="mb-2 h-4 w-4 text-primary"/><div className="text-2xl font-bold">{firstCount}</div><div className="text-xs font-medium">First TD Prices</div></div><div className="rounded-xl border bg-card p-4"><Trophy className="mb-2 h-4 w-4 text-primary"/><div className="text-2xl font-bold">{anytimeCount}</div><div className="text-xs font-medium">Anytime TD Prices</div></div><div className="rounded-xl border bg-card p-4"><ShieldCheck className="mb-2 h-4 w-4 text-primary"/><div className="text-2xl font-bold">{priced}</div><div className="text-xs font-medium">Games Priced</div></div></div>{query.isError?<div className="rounded-md border border-destructive/30 bg-destructive/5 p-5 text-sm text-destructive">NFL market data could not be loaded.</div>:games.length?<div className="grid grid-cols-1 gap-4 xl:grid-cols-2">{games.map(g=>tab==='moneyline'?<MoneylineCard key={g.id} game={g}/>:<PlayerMarketCard key={g.id} game={g} first={tab==='firsttd'}/>)}</div>:<div className="rounded-md border bg-card p-12 text-center text-muted-foreground">No NFL games found in the current slate.</div>}</div></div>
}
