import { useQuery } from "@tanstack/react-query";
import { AlertTriangle, BarChart3, RefreshCw, Target, TrendingUp } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Skeleton } from "@/components/ui/skeleton";

type Bucket = { label: string; predictions: number; wins: number; hitRate: number | null; averagePredicted: number | null; calibrationGap: number | null };
type Performance = { bets: number; wins: number; losses: number; pushes: number; winRate: number | null; unitsRisked: number; unitsProfit: number; roi: number | null; averageOdds: number | null; averageEdge: number | null; averageExpectedValue: number | null };
type Summary = { sampleSize: number; gradedPredictions: number; wins: number; hitRate: number | null; brierScore: number | null; logLoss: number | null; expectedCalibrationError: number | null; averagePredicted: number | null; buckets: Bucket[]; qualifiedPlays: { sampleSize: number; wins: number; hitRate: number | null; averagePredicted: number | null }; performance: Performance; lastPredictionAt: string | null; lastGradedAt: string | null };
const pct = (v: number | null, digits = 1) => v === null || !Number.isFinite(v) ? "—" : `${(v * 100).toFixed(digits)}%`;
const num = (v: number | null, digits = 2) => v === null || !Number.isFinite(v) ? "—" : v.toFixed(digits);
const dateTime = (v: string | null) => v ? new Date(v).toLocaleString("en-US", { timeZone: "America/New_York", month: "short", day: "numeric", hour: "numeric", minute: "2-digit" }) + " ET" : "—";

export default function NRFICalibration() {
  const { data, isLoading, isFetching, error, refetch } = useQuery<Summary>({ queryKey: ["/api/mlb/nrfi/calibration", { days: 30 }], queryFn: async () => { const r = await fetch("/api/mlb/nrfi/calibration?days=30"); if (!r.ok) throw new Error("Calibration unavailable"); return r.json(); }, staleTime: 5 * 60 * 1000 });
  if (isLoading) return <div className="space-y-5"><Skeleton className="h-8 w-72" /><div className="grid grid-cols-1 md:grid-cols-4 gap-4">{Array.from({ length: 4 }).map((_, i) => <Skeleton key={i} className="h-28" />)}</div><Skeleton className="h-80 w-full" /></div>;
  if (error || !data) return <div className="rounded-md border border-destructive/30 bg-destructive/5 p-6"><p className="font-semibold">Calibration data is unavailable.</p><p className="text-sm text-muted-foreground mt-1">The prediction ledger may not have a database connection yet.</p><Button className="mt-4" variant="outline" onClick={() => refetch()}>Retry</Button></div>;
  const p = data.performance; const enoughForTrackRecord = p.bets >= 50;
  return <div className="space-y-6">
    <div className="flex flex-wrap items-start justify-between gap-3"><div><h1 className="text-xl font-bold">NRFI / YRFI Model Audit</h1><p className="text-xs text-muted-foreground mt-1">30-day calibration and sportsbook-value ledger. Historical prices are the locked prices captured at prediction time.</p></div><Button variant="outline" size="sm" onClick={() => refetch()} disabled={isFetching} className="gap-2"><RefreshCw className={isFetching ? "w-3.5 h-3.5 animate-spin" : "w-3.5 h-3.5"} />Refresh</Button></div>
    <div className="rounded-md border bg-primary/5 p-4 flex gap-3"><AlertTriangle className="w-4 h-4 mt-0.5 text-primary shrink-0" /><div><p className="text-sm font-semibold">Read the sample size before reading the ROI.</p><p className="text-xs text-muted-foreground mt-1">A small number of verified bets can move ROI dramatically. {enoughForTrackRecord ? "The current ledger has reached 50+ verified bets, but longer samples are still preferable." : `The ledger has ${p.bets} verified sportsbook bets; it is not yet a statistically strong long-run track record.`}</p></div></div>
    <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">{[{ icon: Target, label: "Verified bets", value: `${p.bets}`, sub: `${p.wins}W · ${p.losses}L` }, { icon: TrendingUp, label: "ROI", value: pct(p.roi), sub: `${p.unitsProfit >= 0 ? "+" : ""}${num(p.unitsProfit, 2)} units` }, { icon: BarChart3, label: "Win rate", value: pct(p.winRate), sub: `${p.unitsRisked} units risked` }, { icon: Target, label: "Avg locked EV", value: pct(p.averageExpectedValue), sub: `Avg edge ${pct(p.averageEdge)}` }].map(({ icon: Icon, label, value, sub }) => <div key={label} className="rounded-md border bg-card p-5"><div className="flex items-center justify-between"><span className="text-[10px] uppercase tracking-wide text-muted-foreground">{label}</span><Icon className="w-4 h-4 text-primary" /></div><p className="text-3xl font-bold font-mono mt-2">{value}</p><p className="text-xs text-muted-foreground mt-1">{sub}</p></div>)}</div>
    <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
      <section className="rounded-md border bg-card p-5"><div className="flex items-center justify-between mb-4"><div><h2 className="font-semibold">Probability calibration</h2><p className="text-xs text-muted-foreground mt-1">Predicted probability vs actual hit rate</p></div><Badge variant="secondary">{data.gradedPredictions} graded</Badge></div><div className="space-y-3">{data.buckets.map(b => <div key={b.label} className="grid grid-cols-[64px_1fr_58px] items-center gap-3"><span className="text-[10px] text-muted-foreground font-mono">{b.label}</span><div className="h-2 rounded-full bg-muted overflow-hidden"><div className="h-full bg-primary rounded-full" style={{ width: `${Math.min(100, Math.max(0, (b.hitRate ?? 0) * 100))}%` }} /></div><span className="text-[10px] text-right font-mono">{pct(b.hitRate)}</span></div>)}</div><div className="grid grid-cols-3 gap-3 mt-5 pt-4 border-t"><div><p className="text-[9px] text-muted-foreground">Brier</p><p className="font-mono text-sm">{num(data.brierScore, 3)}</p></div><div><p className="text-[9px] text-muted-foreground">Log loss</p><p className="font-mono text-sm">{num(data.logLoss, 3)}</p></div><div><p className="text-[9px] text-muted-foreground">ECE</p><p className="font-mono text-sm">{pct(data.expectedCalibrationError)}</p></div></div></section>
      <section className="rounded-md border bg-card p-5"><h2 className="font-semibold">Verified market performance</h2><p className="text-xs text-muted-foreground mt-1">Only value plays with a captured sportsbook price and graded outcome count here.</p><div className="grid grid-cols-2 gap-4 mt-5"><div><p className="text-[9px] text-muted-foreground">Units profit</p><p className={`text-2xl font-bold font-mono ${p.unitsProfit >= 0 ? "text-emerald-500" : "text-red-500"}`}>{p.unitsProfit >= 0 ? "+" : ""}{num(p.unitsProfit)}</p></div><div><p className="text-[9px] text-muted-foreground">Average odds</p><p className="text-2xl font-bold font-mono">{p.averageOdds === null ? "—" : p.averageOdds > 0 ? `+${p.averageOdds.toFixed(0)}` : p.averageOdds.toFixed(0)}</p></div><div><p className="text-[9px] text-muted-foreground">Qualified plays</p><p className="text-2xl font-bold font-mono">{data.qualifiedPlays.sampleSize}</p></div><div><p className="text-[9px] text-muted-foreground">Qualified hit rate</p><p className="text-2xl font-bold font-mono">{pct(data.qualifiedPlays.hitRate)}</p></div></div><div className="mt-5 rounded-md bg-muted/30 p-3 text-[10px] text-muted-foreground">Locked market data is historical evidence, not a guarantee of future results. Missing prices are excluded rather than estimated.</div></section>
    </div>
    <div className="rounded-md border bg-card p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-semibold">Audit trail</h2><p className="text-xs text-muted-foreground mt-1">{data.sampleSize} snapshots · {data.gradedPredictions} graded · last prediction {dateTime(data.lastPredictionAt)} · last grade {dateTime(data.lastGradedAt)}</p></div><Badge className={enoughForTrackRecord ? "bg-emerald-500/15 text-emerald-500 border-emerald-500/30" : "bg-yellow-500/15 text-yellow-600 border-yellow-500/30"}>{enoughForTrackRecord ? "TRACK RECORD DEVELOPING" : "EARLY SAMPLE"}</Badge></div></div>
  </div>;
}
