import { Pool, neonConfig } from '@neondatabase/serverless';
import ws from 'ws';
import { getOpeningPlayerStats, saveOpeningEvidence, verifyOpeningEvidence, type WnbaStarter } from './wnbaEvidence';
import { attachWnbaFirstBasketMarkets, type WnbaFirstBasketMarket } from './odds/parlayWnba';

neonConfig.webSocketConstructor = ws;
const pool = process.env.DATABASE_URL ? new Pool({ connectionString: process.env.DATABASE_URL }) : null;

const MODEL_VERSION = 'WNBA-FB-SEASONAL-V1';
const LOCK_WINDOW_MS = 2 * 60 * 60 * 1000;
const CACHE_TTL_MS = 2 * 60 * 1000;
const PROJECTION_TTL_MS = 5 * 60 * 1000;
let slateCache: { at: number; value: WnbaSlate } | null = null;
const projectionCache = new Map<string,{at:number;starters:Starter[]}>();

type Starter = WnbaStarter;
type HistoryRow = { fbScored: number; gamesTracked: number };
export type WnbaCandidate = {
  name:string; team:string; position:string; headshot:string|null;
  seasonStarts:number; avgPoints:number; avgFga:number; fgPct:number; avgMinutes:number;
  currentFirstBaskets:number; currentGamesTracked:number;
  previousFirstBaskets:number; previousGamesTracked:number;
  openingFirstShots:number; openingFirstShotRate:number|null; openingShotFgPct:number|null;
  probability:number; rank:number; marketOdds?:WnbaFirstBasketMarket|null;
};
export type WnbaTipSignal = {
  awayJumper:string|null; homeJumper:string|null;
  awayTipWins:number; awayTipEvents:number; awayTipPct:number|null;
  homeTipWins:number; homeTipEvents:number; homeTipPct:number|null;
  projectedFirstPossessionTeam:string|null; confidence:'insufficient'|'emerging'|'usable';
};
export type WnbaGame = {
  id:string; date:string; shortName:string; awayTeam:string; homeTeam:string;
  awayName:string; homeName:string; status:string;
  lineupStatus:'confirmed'|'projected'|'waiting'; starters:Starter[]; candidates:WnbaCandidate[];
  topPick:WnbaCandidate|null; tipSignal:WnbaTipSignal;
};
export type WnbaSlate = { season:number; updatedAt:string; teams:{abbreviation:string;name:string}[]; games:WnbaGame[]; source:string; modelVersion:string };

function normalizeName(v:string){return v.toLowerCase().replace(/[.'’\-]/g,'').replace(/\s+/g,' ').trim()}
function normalizeTeam(v:string){return v.toUpperCase().trim()}
function currentSeason(date=new Date()){return date.getUTCFullYear()}
function etDate(date=new Date()){const p=new Intl.DateTimeFormat('en-US',{timeZone:'America/New_York',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(date);return `${p.find(x=>x.type==='year')?.value}${p.find(x=>x.type==='month')?.value}${p.find(x=>x.type==='day')?.value}`}
function compactDate(date:Date){return date.toISOString().slice(0,10).replace(/-/g,'')}
function offsetCompactDate(date:string,days:number){const y=Number(date.slice(0,4)),m=Number(date.slice(4,6)),d=Number(date.slice(6,8));return compactDate(new Date(Date.UTC(y,m-1,d+days,12)))}
async function fetchJson(url:string):Promise<any|null>{try{const r=await fetch(url,{headers:{'User-Agent':'Mozilla/5.0'},signal:AbortSignal.timeout(8000)});return r.ok?await r.json():null}catch{return null}}
async function fetchScoreboard(date=etDate()){
  const buckets=[offsetCompactDate(date,-1),date,offsetCompactDate(date,1)];
  const payloads=await Promise.all(buckets.map(d=>fetchJson(`https://site.api.espn.com/apis/site/v2/sports/basketball/wnba/scoreboard?dates=${d}`)));
  const merged=payloads.flatMap(d=>d?.events||[]);
  const unique=[...new Map(merged.map((event:any)=>[String(event?.id||`${event?.date}-${event?.shortName}`),event])).values()];
  return unique.filter((event:any)=>event?.date&&etDate(new Date(event.date))===date).sort((a:any,b:any)=>new Date(a.date).getTime()-new Date(b.date).getTime());
}

export async function ensureWnbaSchema(){if(!pool)return;await pool.query(`
  CREATE TABLE IF NOT EXISTS wnba_fb_tracking(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),player_name text NOT NULL,team text NOT NULL,season integer NOT NULL,fb_scored integer NOT NULL DEFAULT 0,games_tracked integer NOT NULL DEFAULT 0,last_updated timestamptz NOT NULL DEFAULT now());
  CREATE UNIQUE INDEX IF NOT EXISTS wnba_fb_tracking_unique ON wnba_fb_tracking(lower(player_name),upper(team),season);
  CREATE INDEX IF NOT EXISTS wnba_fb_tracking_season_idx ON wnba_fb_tracking(season);
  CREATE TABLE IF NOT EXISTS wnba_processed_games(espn_game_id text PRIMARY KEY,game_date date,first_scorer text,first_scorer_team text,processed_at timestamptz NOT NULL DEFAULT now());
  CREATE TABLE IF NOT EXISTS wnba_prediction_ledger(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),espn_game_id text NOT NULL,season integer NOT NULL,game_start_at timestamptz NOT NULL,locked_at timestamptz NOT NULL,model_version text NOT NULL,player_name text NOT NULL,team text NOT NULL,model_probability numeric(5,2) NOT NULL,model_rank integer NOT NULL,is_top_pick boolean NOT NULL DEFAULT false,actual_first_scorer text,actual_first_scorer_team text,won boolean,graded_at timestamptz,CONSTRAINT wnba_fb_probability_check CHECK(model_probability>=0 AND model_probability<=100));
  CREATE UNIQUE INDEX IF NOT EXISTS wnba_prediction_game_player_unique ON wnba_prediction_ledger(espn_game_id,lower(player_name),upper(team));
  CREATE INDEX IF NOT EXISTS wnba_prediction_locked_idx ON wnba_prediction_ledger(locked_at DESC);
`)}
async function getHistory(season:number){const out=new Map<string,HistoryRow>();if(!pool)return out;await ensureWnbaSchema();const r=await pool.query('SELECT player_name,team,fb_scored,games_tracked FROM wnba_fb_tracking WHERE season=$1',[season]);for(const x of r.rows)out.set(`${normalizeName(x.player_name)}|${normalizeTeam(x.team)}`,{fbScored:Number(x.fb_scored),gamesTracked:Number(x.games_tracked)});return out}
async function fetchTeams(){const d=await fetchJson('https://site.api.espn.com/apis/site/v2/sports/basketball/wnba/teams?limit=50');return(d?.sports?.[0]?.leagues?.[0]?.teams||[]).map((e:any)=>({abbreviation:String(e?.team?.abbreviation||'').toUpperCase(),name:String(e?.team?.displayName||'')})).filter((t:any)=>t.abbreviation&&t.name)}
async function fetchSummary(id:string){return fetchJson(`https://site.api.espn.com/apis/site/v2/sports/basketball/wnba/summary?event=${id}`)}
function extractStarters(summary:any):Starter[]{const out:Starter[]=[];for(const b of summary?.boxscore?.players||[]){const team=normalizeTeam(String(b?.team?.abbreviation||''));for(const g of b?.statistics||[])for(const row of g?.athletes||[]){if(row?.starter!==true||row?.didNotPlay===true)continue;const name=String(row?.athlete?.displayName||'').trim();if(name&&team)out.push({name,team})}}return[...new Map(out.map(s=>[`${normalizeName(s.name)}|${s.team}`,s])).values()]}
async function fetchRoster(team:string){const d=await fetchJson(`https://site.api.espn.com/apis/site/v2/sports/basketball/wnba/teams/${team}/roster`);return d?.athletes||[]}
function rosterStatusText(player:any){const injuries=Array.isArray(player?.injuries)?player.injuries:[];return [player?.status?.type,player?.status?.name,player?.status?.description,player?.status?.detail,...injuries.flatMap((x:any)=>[x?.status,x?.type,x?.details,x?.description])].filter(Boolean).join(' ').toLowerCase()}
function isUnavailableRosterPlayer(player:any){const text=rosterStatusText(player);return /\b(out|inactive|suspended|waived|injured reserve|season[- ]ending|not with team)\b/.test(text)}

async function fetchPlayerStats(id:string,season:number){const d=await fetchJson(`https://sports.core.api.espn.com/v2/sports/basketball/leagues/wnba/seasons/${season}/types/2/athletes/${id}/statistics/0`);const cats=d?.splits?.categories;if(!cats)return null;const all=(cats||[]).flatMap((c:any)=>c?.stats||[]);const n=(names:string[])=>{for(const name of names){const s=all.find((x:any)=>String(x?.name||'').toLowerCase()===name.toLowerCase());if(s){const v=Number.parseFloat(String(s?.value??s?.displayValue??'0').replace(/[^0-9.-]/g,''));if(Number.isFinite(v))return v}}return 0};return{games:n(['gamesPlayed','games']),starts:n(['gamesStarted','starts']),points:n(['avgPoints','pointsPerGame']),fga:n(['avgFieldGoalsAttempted','fieldGoalsAttemptedPerGame']),fg:n(['fieldGoalPct','fieldGoalPercentage']),minutes:n(['avgMinutes','minutesPerGame'])}}

async function latestProjectedStarters(team:string):Promise<Starter[]>{const key=normalizeTeam(team),cached=projectionCache.get(key);if(cached&&Date.now()-cached.at<PROJECTION_TTL_MS)return cached.starters;const roster=await fetchRoster(key);if(!roster.length){projectionCache.set(key,{at:Date.now(),starters:[]});return[]}const available=new Set(roster.filter((x:any)=>!isUnavailableRosterPlayer(x)).map((x:any)=>normalizeName(String(x?.displayName||''))).filter(Boolean));for(let day=1;day<=14;day++){const date=new Date(Date.now()-day*86400000);const events=await fetchScoreboard(compactDate(date));for(const e of events.filter((x:any)=>x?.status?.type?.completed===true)){const comp=e?.competitions?.[0];const has=(comp?.competitors||[]).some((c:any)=>normalizeTeam(String(c?.team?.abbreviation||''))===key);if(!has)continue;const s=extractStarters(await fetchSummary(String(e.id))).filter(x=>x.team===key);if(s.length===5){const valid=s.every(x=>available.has(normalizeName(x.name)));const starters=valid?s:[];projectionCache.set(key,{at:Date.now(),starters});return starters}}}projectionCache.set(key,{at:Date.now(),starters:[]});return[]}

function opportunityProbability(stats:any,position:string,openingRate:number|null){if(!stats)return 4;let score=(stats.fga/75)*38+(stats.points/35)*8+((stats.fg-42)/30)*4+(Math.min(stats.minutes,36)/36)*3;if(position==='C')score*=1.10;else if(position==='PG')score*=1.04;if(openingRate!==null)score=score*0.9+Math.min(openingRate,35)*0.1;return Math.max(2,Math.min(32,score))}
function blend(model:number,prev:HistoryRow|undefined,cur:HistoryRow|undefined){let num=model*12,den=12;if(prev?.gamesTracked){const n=Math.min(prev.gamesTracked,12);num+=(prev.fbScored/prev.gamesTracked*100)*n;den+=n}if(cur?.gamesTracked){const n=Math.min(cur.gamesTracked,20);num+=(cur.fbScored/cur.gamesTracked*100)*n;den+=n}return Math.round(Math.max(1,Math.min(35,num/den))*10)/10}

async function modelStarters(starters:Starter[],season:number):Promise<WnbaCandidate[]>{if(starters.length!==10)return[];const[current,previous,opening]=await Promise.all([getHistory(season),getHistory(season-1),getOpeningPlayerStats(season)]);const teams=[...new Set(starters.map(s=>s.team))],rosters=new Map<string,any[]>();await Promise.all(teams.map(async t=>rosters.set(t,await fetchRoster(t))));const out:WnbaCandidate[]=[];for(const s of starters){const roster=rosters.get(s.team)||[],norm=normalizeName(s.name);let p=roster.find((x:any)=>normalizeName(String(x?.displayName||''))===norm);if(!p){const last=norm.split(' ').at(-1);p=roster.find((x:any)=>normalizeName(String(x?.displayName||'')).split(' ').at(-1)===last)}if(!p?.id||isUnavailableRosterPlayer(p))continue;const stats=await fetchPlayerStats(String(p.id),season),position=String(p?.position?.abbreviation||'G'),key=`${norm}|${s.team}`,cur=current.get(key),prev=previous.get(key),op=opening.get(norm),verifiedStarts=cur?.gamesTracked||0,openingRate=verifiedStarts>0?Math.round(((op?.firstShots||0)/verifiedStarts)*1000)/10:null,openingFg=(op?.firstShots||0)>0?Math.round(((op?.firstMakes||0)/(op?.firstShots||1))*1000)/10:null;out.push({name:s.name,team:s.team,position,headshot:p?.headshot?.href||null,seasonStarts:Math.round(stats?.starts||0),avgPoints:Math.round((stats?.points||0)*10)/10,avgFga:Math.round((stats?.fga||0)*10)/10,fgPct:Math.round((stats?.fg||0)*10)/10,avgMinutes:Math.round((stats?.minutes||0)*10)/10,currentFirstBaskets:cur?.fbScored||0,currentGamesTracked:verifiedStarts,previousFirstBaskets:prev?.fbScored||0,previousGamesTracked:prev?.gamesTracked||0,openingFirstShots:op?.firstShots||0,openingFirstShotRate:openingRate,openingShotFgPct:openingFg,probability:blend(opportunityProbability(stats,position,openingRate),prev,cur),rank:0})}out.sort((a,b)=>b.probability-a.probability).forEach((p,i)=>p.rank=i+1);return out}

function eventTeams(event:any){const c=event?.competitions?.[0];return{away:c?.competitors?.find((x:any)=>x.homeAway==='away'),home:c?.competitors?.find((x:any)=>x.homeAway==='home')}}
function frontcourtRank(position:string){const p=position.toUpperCase();if(p==='C')return 4;if(p==='F-C'||p==='C-F')return 3;if(p==='PF'||p==='F')return 2;return 0}
function tipNameKey(v:string){return normalizeName(String(v||'').split(':')[0])}
function sameTipPlayer(stored:string,fullName:string){const a=tipNameKey(stored),b=normalizeName(fullName);if(!a||!b)return false;if(a===b)return true;const last=b.split(' ').at(-1)||b;return a===last}
async function playerTipStats(name:string,team:string,season:number){if(!pool)return{wins:0,events:0,pct:null as number|null};await ensureWnbaSchema();const r=await pool.query(`SELECT tip_winner_team,tip_player_a,tip_player_b,team_a,team_b FROM wnba_opening_evidence WHERE extract(year from game_date)::int IN ($1::int, ($1::int - 1)) AND confidence='verified' AND tip_winner_team IS NOT NULL AND (upper(team_a)=upper($2) OR upper(team_b)=upper($2))`,[season,team]);const rows=r.rows.filter(x=>sameTipPlayer(String(x.tip_player_a||''),name)||sameTipPlayer(String(x.tip_player_b||''),name));const events=rows.length,wins=rows.filter(x=>normalizeTeam(String(x.tip_winner_team||''))===normalizeTeam(team)).length;return{wins,events,pct:events?Math.round(wins/events*1000)/10:null}}
async function selectJumper(candidates:WnbaCandidate[],team:string,season:number){const teamPlayers=candidates.filter(c=>c.team===team);if(!teamPlayers.length)return null;const enriched=await Promise.all(teamPlayers.map(async c=>({player:c,stats:await playerTipStats(c.name,team,season)})));const historical=enriched.filter(x=>x.stats.events>0).sort((a,b)=>b.stats.events-a.stats.events||frontcourtRank(b.player.position)-frontcourtRank(a.player.position)||b.player.avgMinutes-a.player.avgMinutes);if(historical.length)return historical[0];const frontcourt=enriched.filter(x=>frontcourtRank(x.player.position)>0).sort((a,b)=>frontcourtRank(b.player.position)-frontcourtRank(a.player.position)||b.player.avgMinutes-a.player.avgMinutes);return frontcourt[0]||null}
async function tipSignal(away:string,home:string,candidates:WnbaCandidate[]):Promise<WnbaTipSignal>{const season=currentSeason(),[aj,hj]=await Promise.all([selectJumper(candidates,away,season),selectJumper(candidates,home,season)]),a=aj?.stats||{wins:0,events:0,pct:null},h=hj?.stats||{wins:0,events:0,pct:null},ap=a.pct,hp=h.pct,total=a.events+h.events,confidence=total>=20?'usable':total>=8?'emerging':'insufficient';let projected:string|null=null;if(confidence!=='insufficient'&&ap!==null&&hp!==null&&Math.abs(ap-hp)>=5)projected=ap>hp?away:home;return{awayJumper:aj?.player.name||null,homeJumper:hj?.player.name||null,awayTipWins:a.wins,awayTipEvents:a.events,awayTipPct:ap,homeTipWins:h.wins,homeTipEvents:h.events,homeTipPct:hp,projectedFirstPossessionTeam:projected,confidence}}

export async function getWnbaSlate(force=false):Promise<WnbaSlate>{if(!force&&slateCache&&Date.now()-slateCache.at<CACHE_TTL_MS)return slateCache.value;await ensureWnbaSchema();const season=currentSeason(),[teams,events]=await Promise.all([fetchTeams(),fetchScoreboard()]),games:WnbaGame[]=[];for(const event of events){const{away,home}=eventTeams(event);if(!away||!home)continue;const awayTeam=normalizeTeam(away.team.abbreviation),homeTeam=normalizeTeam(home.team.abbreviation),summary=await fetchSummary(String(event.id)),confirmed=summary?extractStarters(summary):[];let starters=confirmed,lineupStatus:WnbaGame['lineupStatus']='waiting';if(confirmed.length===10){lineupStatus='confirmed'}else{const[a,h]=await Promise.all([latestProjectedStarters(awayTeam),latestProjectedStarters(homeTeam)]);starters=[...a,...h];if(starters.length===10)lineupStatus='projected'}let candidates=starters.length===10?await modelStarters(starters,season):[];if(candidates.length!==10&&lineupStatus==='projected'){starters=[];lineupStatus='waiting'}if(lineupStatus!=='waiting'&&candidates.length){candidates=await attachWnbaFirstBasketMarkets(candidates)}games.push({id:String(event.id),date:event.date,shortName:event.shortName||`${awayTeam} @ ${homeTeam}`,awayTeam,homeTeam,awayName:away.team.displayName,homeName:home.team.displayName,status:event?.status?.type?.description||event?.status?.type?.state||'Scheduled',lineupStatus,starters,candidates:lineupStatus==='waiting'?[]:candidates,topPick:lineupStatus==='waiting'?null:candidates[0]||null,tipSignal:await tipSignal(awayTeam,homeTeam,lineupStatus==='waiting'?[]:candidates)})}const value={season,updatedAt:new Date().toISOString(),teams,games,source:'ESPN WNBA schedule/roster/boxscore/play-by-play + verified PreziBaskets opening evidence + ParlayAPI FanDuel/DraftKings first-basket market prices when available',modelVersion:MODEL_VERSION};slateCache={at:Date.now(),value};return value}

async function recordVerifiedGame(gameId:string,gameDate:string,starters:Starter[],scorer:Starter,season:number){if(!pool||starters.length!==10)return;await ensureWnbaSchema();const c=await pool.connect();try{await c.query('BEGIN');const ex=await c.query('SELECT 1 FROM wnba_processed_games WHERE espn_game_id=$1',[gameId]);if(ex.rows.length){await c.query('ROLLBACK');return}for(const s of starters){const won=normalizeName(s.name)===normalizeName(scorer.name)&&normalizeTeam(s.team)===normalizeTeam(scorer.team);await c.query(`INSERT INTO wnba_fb_tracking(player_name,team,season,fb_scored,games_tracked,last_updated) VALUES($1,$2,$3,$4,1,now()) ON CONFLICT(lower(player_name),upper(team),season) DO UPDATE SET fb_scored=wnba_fb_tracking.fb_scored+EXCLUDED.fb_scored,games_tracked=wnba_fb_tracking.games_tracked+1,last_updated=now()`,[s.name,s.team,season,won?1:0])}await c.query('INSERT INTO wnba_processed_games(espn_game_id,game_date,first_scorer,first_scorer_team) VALUES($1,$2,$3,$4)',[gameId,gameDate,scorer.name,scorer.team]);await c.query(`UPDATE wnba_prediction_ledger SET actual_first_scorer=$2,actual_first_scorer_team=$3,won=(lower(player_name)=lower($2) AND upper(team)=upper($3)),graded_at=now() WHERE espn_game_id=$1 AND graded_at IS NULL`,[gameId,scorer.name,scorer.team]);await c.query('COMMIT')}catch(e){await c.query('ROLLBACK');throw e}finally{c.release()}slateCache=null}

export async function runWnbaTracker(){await ensureWnbaSchema();let processed=0,unresolved=0;for(const offset of[0,-1]){const events=await fetchScoreboard(etDate(new Date(Date.now()+offset*86400000)));for(const event of events.filter((e:any)=>e?.status?.type?.completed===true)){if(pool){const done=await pool.query('SELECT 1 FROM wnba_processed_games WHERE espn_game_id=$1',[String(event.id)]);if(done.rows.length)continue}const summary=await fetchSummary(String(event.id)),starters=summary?extractStarters(summary):[],evidence=summary?verifyOpeningEvidence(String(event.id),String(event.date).slice(0,10),summary,starters):null;if(starters.length!==10||!evidence){unresolved++;continue}await saveOpeningEvidence(evidence);await recordVerifiedGame(String(event.id),String(event.date).slice(0,10),starters,{name:evidence.firstMadePlayer,team:evidence.firstMadeTeam},currentSeason(new Date(event.date)));processed++}}return{processed,unresolved}}

export async function lockWnbaPredictions(){if(!pool)return{eligible:0,locked:0,waiting:0,upgraded:0};await ensureWnbaSchema();const now=Date.now(),events=await fetchScoreboard();let eligible=0,locked=0,waiting=0,upgraded=0;for(const event of events){const start=new Date(event.date).getTime();if(!Number.isFinite(start)||start<=now||start-now>LOCK_WINDOW_MS)continue;eligible++;const{away,home}=eventTeams(event);if(!away||!home){waiting++;continue}const awayTeam=normalizeTeam(String(away?.team?.abbreviation||'')),homeTeam=normalizeTeam(String(home?.team?.abbreviation||''));const existing=await pool.query('SELECT model_version FROM wnba_prediction_ledger WHERE espn_game_id=$1 LIMIT 1',[String(event.id)]),existingVersion=String(existing.rows[0]?.model_version||''),existingProjected=existing.rows.length>0&&existingVersion.endsWith('-PROJECTED');const summary=await fetchSummary(String(event.id));let starters=summary?extractStarters(summary):[];let snapshotVersion=MODEL_VERSION;if(starters.length===10){if(existing.rows.length&&!existingProjected)continue}else{if(existing.rows.length)continue;const[a,h]=await Promise.all([latestProjectedStarters(awayTeam),latestProjectedStarters(homeTeam)]);starters=[...a,...h];if(starters.length===10)snapshotVersion=`${MODEL_VERSION}-PROJECTED`}if(starters.length!==10){waiting++;continue}const candidates=await modelStarters(starters,currentSeason(new Date(event.date)));if(candidates.length!==10){waiting++;continue}if(existingProjected&&snapshotVersion===MODEL_VERSION){const c=await pool.connect();try{await c.query('BEGIN');await c.query('DELETE FROM wnba_prediction_ledger WHERE espn_game_id=$1',[String(event.id)]);for(const x of candidates)await c.query(`INSERT INTO wnba_prediction_ledger(espn_game_id,season,game_start_at,locked_at,model_version,player_name,team,model_probability,model_rank,is_top_pick) VALUES($1,$2,$3,now(),$4,$5,$6,$7,$8,$9)`,[String(event.id),currentSeason(new Date(event.date)),event.date,snapshotVersion,x.name,x.team,x.probability,x.rank,x.rank===1]);await c.query('COMMIT');upgraded++;locked++;}catch(e){await c.query('ROLLBACK');throw e}finally{c.release()}continue}for(const x of candidates)await pool.query(`INSERT INTO wnba_prediction_ledger(espn_game_id,season,game_start_at,locked_at,model_version,player_name,team,model_probability,model_rank,is_top_pick) VALUES($1,$2,$3,now(),$4,$5,$6,$7,$8,$9) ON CONFLICT DO NOTHING`,[String(event.id),currentSeason(new Date(event.date)),event.date,snapshotVersion,x.name,x.team,x.probability,x.rank,x.rank===1]);locked++}return{eligible,locked,waiting,upgraded}}

export async function getWnbaDiagnostics(days=30){if(!pool)return{modelVersion:MODEL_VERSION,trackedPlayers:0,processedGames:0,openingEvidence:0,lockedGames:0,gradedGames:0,topPickWins:0,topPickAccuracy:null};await ensureWnbaSchema();const r=(await pool.query(`SELECT (SELECT count(*) FROM wnba_fb_tracking WHERE season=$1) tracked_players,(SELECT count(*) FROM wnba_processed_games) processed_games,(SELECT count(*) FROM wnba_opening_evidence WHERE confidence='verified') opening_evidence,(SELECT count(DISTINCT espn_game_id) FROM wnba_prediction_ledger WHERE locked_at>=now()-($2::text||' days')::interval) locked_games,(SELECT count(DISTINCT espn_game_id) FROM wnba_prediction_ledger WHERE graded_at IS NOT NULL AND locked_at>=now()-($2::text||' days')::interval) graded_games,(SELECT count(*) FROM wnba_prediction_ledger WHERE is_top_pick AND won=true AND locked_at>=now()-($2::text||' days')::interval) top_wins,(SELECT count(*) FROM wnba_prediction_ledger WHERE is_top_pick AND graded_at IS NOT NULL AND locked_at>=now()-($2::text||' days')::interval) top_graded`,[currentSeason(),Math.max(1,Math.min(days,365))])).rows[0]||{},g=Number(r.top_graded||0),w=Number(r.top_wins||0);return{modelVersion:MODEL_VERSION,trackedPlayers:Number(r.tracked_players||0),processedGames:Number(r.processed_games||0),openingEvidence:Number(r.opening_evidence||0),lockedGames:Number(r.locked_games||0),gradedGames:Number(r.graded_games||0),topPickWins:w,topPickAccuracy:g?Math.round(w/g*1000)/10:null}}
